### ISSUE TITLE
Installation fehlgeschlagen

### ISSUE THREAD

**Issue by Nathanael-L** [kreis-viersen/flurstuecksfinder-nrw#56]
Guten Tag zusammen,

die Installation des Plugins klappt nicht. Ich verwende QGIS 3.22.12 LTR unter Windows, installiert mit OSGeo4W.

Ich bekomme den Fehler:
```
Konnte Erweiterung 'flurstuecksfinder-nrw' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'lxml' 
```

Installiert das Plugin normalerweise `lxml` selbst?

Grüße

**Comment by pathmapper** [comment]
Hallo @Nathanael-L,

> Installiert das Plugin normalerweise lxml selbst?

Nein.

Das Modul wird mit dem QGIS-Standalone-Installer automatisch mit installiert, bei Verwendung des OSGeo4W-Installers kann man das Modull zur Installation auswählen (unter ``libs``):

![lxml](https://user-images.githubusercontent.com/20856381/220295529-1dd0ba56-9db6-4451-8a15-e33226288413.PNG)

`lxml` wird übrigens auch von einigen weiteren QGIS-Plugins verwendet.

Hilft das soweit?

Viele Grüße

**Comment by pathmapper** [comment]
Wir werden den Fehler in Zukunft abfangen und statt dessen eine Meldung mit dem fehlenden Modul ausgeben, danke für die Rückmeldung!
